// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20261009113200_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.AirlineCompany", b =>
                {
                    b.Property<Guid>("AirlineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("AirlineID");

                    b.ToTable("AirlineCompanies");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airplane", b =>
                {
                    b.Property<Guid>("AirplaneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirlineID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AirportID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ManufacturingDate")
                        .HasColumnType("date");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("SpecificFlight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirplaneID");

                    b.HasIndex("AirlineID");

                    b.HasIndex("AirportID");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.AirplaneChanges", b =>
                {
                    b.Property<Guid>("ChangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirportID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChangeID");

                    b.HasIndex("AirportID");

                    b.ToTable("AirplaneChanges");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airport", b =>
                {
                    b.Property<Guid>("AirportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TerminalID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AirportID");

                    b.HasIndex("TerminalID");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Gate", b =>
                {
                    b.Property<Guid>("GateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GateLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GateNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TerminalID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GateID");

                    b.HasIndex("TerminalID");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Luggage", b =>
                {
                    b.Property<Guid>("LuggageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LuggageNumber")
                        .HasColumnType("int");

                    b.Property<string>("LuggageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("LuggageID");

                    b.ToTable("Luggages");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Passenger", b =>
                {
                    b.Property<Guid>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AirportID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DocumentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LuggageAmount")
                        .HasColumnType("int");

                    b.Property<Guid?>("LuggageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("TicketID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PassengerID");

                    b.HasIndex("AirportID");

                    b.HasIndex("LuggageID");

                    b.HasIndex("TicketID");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.Property<Guid>("TerminalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TerminalLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TerminalNumber")
                        .HasColumnType("int");

                    b.HasKey("TerminalID");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Ticket", b =>
                {
                    b.Property<Guid>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GateID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("TerminalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketID");

                    b.HasIndex("GateID");

                    b.HasIndex("TerminalID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airplane", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.AirlineCompany", "AirlineCompany")
                        .WithMany()
                        .HasForeignKey("AirlineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Airport", null)
                        .WithMany("Airplanes")
                        .HasForeignKey("AirportID");

                    b.Navigation("AirlineCompany");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.AirplaneChanges", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Airport", "AirlineCompany")
                        .WithMany()
                        .HasForeignKey("AirportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineCompany");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airport", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Gate", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Passenger", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportID");

                    b.HasOne("DatabaseTask.Core.Domain.Luggage", "Luggage")
                        .WithMany()
                        .HasForeignKey("LuggageID");

                    b.HasOne("DatabaseTask.Core.Domain.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketID");

                    b.Navigation("Airport");

                    b.Navigation("Luggage");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Ticket", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("GateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalID");

                    b.Navigation("Gate");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airport", b =>
                {
                    b.Navigation("Airplanes");
                });
#pragma warning restore 612, 618
        }
    }
}
